# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170126_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=32),
        ),
    ]
